- id: '1530556498503'
  alias: Set off alarm while armed away
  trigger:
  - entity_id: binary_sensor.ians_left_window_status
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.ians_entry_door_status
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.ians_right_window_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  action:
  - alias: ''
    data: {}
    service: alarm_control_panel.alarm_trigger
  hide_entity: true
- id: '1530909494277'
  alias: Set off alarm while armed night
  trigger:
  - entity_id: binary_sensor.ians_left_window_status
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.ians_right_window_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_night
  action:
  - service: alarm_control_panel.alarm_trigger
  hide_entity: True
- id: '1530909572420'
  alias: Set off alarm while armed home
  trigger:
  - entity_id: binary_sensor.ians_left_window_status
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.ians_right_window_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_home
  action:
  - service: alarm_control_panel.alarm_trigger
  hide_entity: True

