# Home assistant config - v0.3.0
# 2019-02-24T16:30

# Backend
homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elev
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include config/customize.yaml

updater:
  include_used_components: true

mqtt:
    broker: !secret mqtt_ip
    discovery: true
    discovery_prefix: homeassistant

influxdb:
  host: !secret influx_host
  database: home_assistant
  username: !secret influx_username
  password: !secret influx_password

group: !include config/groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

# Web Interface
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

panel_iframe: !include config/iframe.yaml

conversation:

tts: !include config/tts.yaml

recorder:
    purge_keep_days: 5
    purge_interval: 1

map:

logbook:

history:

config:

system_health:

ios: !include config/ios.yaml

homekit:

notify: !include config/notify.yaml

# Map Zones
zone: !include config/zone.yaml

# Sensors
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api

speedtestdotnet:
  scan_interval:
    minutes: 5
  monitored_conditions:
    - ping
    - download
    - upload

sensor: !include config/sensor.yaml

binary_sensor: !include config/binary_sensor.yaml

switch: !include config/switch.yaml

light: !include config/light.yaml

device_tracker: !include config/device_tracker.yaml

person:

camera: !include config/camera.yaml

shopping_list:

apple_tv:
  - host: !secret apple_tv_ip
    name: Apple Tv
    login_id: !secret apple_tv_login

media_player: !include config/media_player.yaml

geo_location: !include config/geo_location.yaml

aqualink:
  username: !secret pool_user
  password: !secret pool_pass

# Alarm
alarm_control_panel: !include config/alarm.yaml
