# Home assistant config - v0.4.0
# 2019-06-17T13:33

# Backend
homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elev
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include customize.yaml

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

recorder: !include config_components/backend_recorder.yaml

logger: !include config_components/backend_logger.yaml

updater:
  include_used_components: true

custom_updater: !include config_components/backend_custom_updater.yaml

mqtt: !include config_components/backend_mqtt.yaml

# Web Frontend
http:
  base_url: !secret base_url

conversation:

frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom-fa/solid.html
    - /local/custom-fa/regular.html
    - /local/custom-fa/brands.html

lovelace:
  mode: yaml

map:

zone: !include config_components/frontend_zone.yaml

logbook:

history:

panel_iframe: !include config_components/frontend_iframe.yaml

config:

system_health:

# Mobile Frontend
ios: !include config_components/frontend_ios.yaml

mobile_app:

# Components
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

speedtestdotnet: !include config_components/component_speedtest.yaml

alarm_control_panel: !include config_components/component_alarm.yaml

sensor: !include config_components/component_sensor.yaml

binary_sensor: !include config_components/component_sensor_binary.yaml

switch: !include config_components/component_switch.yaml

light: !include config_components/component_light.yaml

media_player: !include config_components/component_media_player.yaml

apple_tv: !include config_components/component_media_player_appletv.yaml

alexa_media: !include config_components/component_media_player_alexa.yaml

person:

device_tracker: !include config_components/component_device_tracker.yaml

geo_location: !include config_components/component_geo_location.yaml

sun:

weather: !include config_components/component_weather.yaml

aqaulink: !include config_components/component_pool_aqualink.yaml

notify: !include config_components/component_notify.yaml

telegram_bot: !include config_components/component_notify_telegram.yaml

tts: !include config_components/component_tts.yaml

input_boolean: !include config_components/component_input_boolean.yaml
