resources: !include lovelace/00_resources.yaml
popup_cards: !include lovelace/00_popup_definition.yaml

title: Home
views:
  - !include lovelace/01_home_view.yaml
  - !include lovelace/02_media_view.yaml
  - !include lovelace/03_pool_view.yaml
  - !include lovelace/04_alarm_view.yaml
  - !include lovelace/05_weather_view.yaml
  - !include lovelace/06_network_view.yaml
  - !include lovelace/07_setting_view.yaml
