resources: !include config_lovelace/00_resources.yaml
popup_cards: !include config_lovelace/00_popup_definition.yaml

title: Home
views:
  - !include config_lovelace/01_home_view.yaml
  - !include config_lovelace/02_media_view.yaml
  - !include config_lovelace/03_pool_view.yaml
  - !include config_lovelace/04_alarm_view.yaml
  - !include config_lovelace/05_weather_view.yaml
  - !include config_lovelace/06_network_view.yaml
  - !include config_lovelace/07_setting_view.yaml
