# Main Home Alarm
- platform: manual_mqtt
  name: "Alarm"
  state_topic: home/alarm/state
  command_topic: home/alarm/command
  code: !secret alarm_code
  pending_time: 30
  delay_time: 20
  trigger_time: 120
  disarmed:
    trigger_time: 0
  armed_home:
    pending_time: 0
    delay_time: 0
  armed_night:
    pending_time: 0
    delay_time: 0
  triggered:
    pending_time: 0
