- platform: nmap_tracker
  hosts: 192.168.1.0/24
  exclude:
    - 192.168.1.66
    - 192.168.1.67
  home_interval: 10

- platform: unifi
  host: !secret unifi_host
  verify_ssl: false
  username: !secret unifi_user
  password: !secret unifi_pass
  ssid_filter:
    - !secret main_network_ssid
    - !secret guest_network_ssid
