  pihole:
    title: 'Pi Hole'
    icon: 'mdi:dns'
    url: !secret pi_hole_url
  grafana:
    title: 'Grafana'
    icon: 'mdi:chart-timeline'
    url: !secret grafana_url
  portainer:
    title: 'Portainer'
    icon: 'mdi:docker'
    url: !secret portainer_url
