push:
  categories:
    - name: cameras
      identifier: 'camera'
      actions:
        - identifier: 'TRIGGER_ALARM'
          title: 'Trigger Alarm'
          destructive: 'true'
        - identifier: 'TTS_MESSAGE'
          title: 'TTS Message'
          behavior: 'textInput'
          textInputButtonTitle: 'Send TTS'
          textInputPlaceholder: 'What are you doing?'
