broker: !secret mqtt_ip
discovery: true
discovery_prefix: homeassistant
birth_message:
  topic: 'home/hass/status'
  payload: 'online'
will_message:
  topic: 'home/hass/status'
  payload: 'offline'
