nws_popup_on_wx_alert:
  alias: NWS Weather Alert Pop Up
  sequence:
    - service: persistent_notification.dismiss
      data:
        notification_id: "nwswxalert"
    - service_template: >
        {% if states.sensor.nws_alerts.state != 'None' %}
          persistent_notification.create
        {% endif %}
      data_template:
        notification_id: "nwswxalert"
        message: "{{ message }}"
        title: "{{ title }}"
